set -g base-index 1
setw -g pane-base-index 1
set -g status-style 'bg=#333333 fg=#C3B1E1'
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set-option -g default-shell $SHELL
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
<<<<<<< HEAD
bind-key x kill-pane
=======
set -g mouse on 
>>>>>>> 000d348 (tmux scrolling =))

# set-window-option -g mode-keys vi
set -g mode-keys vi
set -g mouse on
set -g set-clipboard on

# WSL: pipe tmux copy to Windows clipboard
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "clip.exe"

set -g set-clipboard on

set -g mode-keys vi

# vim keybinds
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
