set -g base-index 1
setw -g pane-base-index 1
set -g status-style 'bg=#333333 fg=#C3B1E1'
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set-option -g default-shell $SHELL
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-window-option -g mode-keys vi

# vim keybinds

bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
